identidoc:
  build: .
  ports:
   - "5000:5000"
  environment:
    ENV: DEV 
  volumes:
    - ./app:/app
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster:latest
  ports:
    - "8181:8080"

redis:
  image: redis:5.0
